### ISSUE TITLE
Fill changelog

### ISSUE THREAD

**Issue by cblp** [cblp/crdt#15]

**Comment by dpwiz** [comment]
http://keepachangelog.com/en/1.0.0/

**Comment by cblp** [comment]
@wiz, https://github.com/cblp/crdt/blob/master/CHANGELOG.md

**Comment by dpwiz** [comment]
Осталось дозаполнить, ага.

**Comment by cblp** [comment]
Now [ron](https://hackage.haskell.org/package/ron) is the main CRDT package.
